image: docker:latest

services:
  - name: docker:dind
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]


stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" -f Dockerfile.prod .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
  only:
    - main
    - manual
