stages:
  - build

variables:
  IMAGE_TAG: "latest"
  DOCKER_HOST: tcp://docker:2375

services:
  - name: docker:24.0.5-dind
    alias: docker
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock", "--tls=false"]

build:
  stage: build
  image: docker:24.0.5
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --build-arg DISCORD_WEBHOOK_URL="$DISCORD_WEBHOOK_URL" -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  only:
    - main
